export const GET_GROUP_LIST = 'GET_GROUP_LIST';
export const GET_GROUP_LIST_SUCCESS = 'GET_GROUP_LIST_SUCCESS';
export const GET_GROUP_INFO = 'GET_GROUP_INFO';
export const GET_GROUP_INFO_SUCCESS = 'GET_GROUP_INFO_SUCCESS';