export const GET_GROUP_LIST = 'GET_GROUP_LIST';
export const GET_GROUP_LIST_SUCCESS = 'GET_GROUP_LIST_SUCCESS';

export const GET_GROUP_INFO = 'GET_GROUP_INFO';
export const GET_GROUP_INFO_SUCCESS = 'GET_GROUP_INFO_SUCCESS';

export const ADD_GROUP = 'ADD_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const EDIT_GROUP_SUCCESS = 'EDIT_GROUP_SUCCESS';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'

export const OPEN_ADD_GROUP_FORM = 'OPEN_ADD_GROUP_FORM';
export const OPEN_EDIT_GROUP_FORM = 'OPEN_EDIT_GROUP_FORM';
export const RESET_GROUP = 'CLOSE_GROUP_FORM';