export const GET_BOARD_LIST = 'GET_BOARD_LIST';
export const GET_BOARD_LIST_SUCCESS = 'GET_BOARD_LIST_SUCCESS';

export const GET_BOARD_DETAIL = 'GET_BOARD_DETAIL';
export const GET_BOARD_DETAIL_SUCCESS = 'GET_BOARD_DETAIL_SUCCESS';

export const GET_ALL_BOARDS = 'GET_ALL_BOARDS';
export const SET_ALL_BOARDS = 'SET_ALL_BOARDS';

export const CREATE_BOARD = 'CREATE_BOARD';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_FAIL = 'CREATE_BOARD_FAIL';
export const RESET_CREATE_BOARD_STATUS = "RESET_CREATE_BOARD_STATUS";

export const UPDATE_BOARD = 'UPDATE_BOARD';
export const UPDATE_BOARD_SUCCESS = 'UPDATE_BOARD_SUCCESS';
export const UPDATE_BOARD_FAIL = 'UPDATE_BOARD_FAIL';
