export const GET_BOARD_LIST = 'GET_BOARD_LIST';
export const GET_BOARD_LIST_SUCCESS = 'GET_BOARD_LIST_SUCCESS';
export const GET_BOARD_DETAIL = 'GET_BOARD_DETAIL';
export const GET_BOARD_DETAIL_SUCCESS = 'GET_BOARD_LIST_FAIL_SUCCESS';