export const GET_CARDS = 'GET_CARDS';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
export const GET_CARDS_FAILURE = 'GET_CARDS_FAILURE';

export const GET_CARD_DETAIL = 'GET_CARD_DETAIL';
export const GET_CARD_DETAIL_SUCCESS = 'GET_CARD_DETAIL_SUCCESS';
export const GET_CARD_DETAIL_FAILURE = 'GET_CARD_DETAIL_FAILURE';

export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_CARD_DETAIL = 'CLEAR_CARD_DETAIL';

export const UPDATE_CARD_DETAIL = 'UPDATE_CARD';
export const UPDATE_CARD_DETAIL_SUCCESS = 'UPDATE_CARD_SUCCESS';
export const UPDATE_CARD_DETAIL_FAILURE = 'UPDATE_CARD_FAILURE';

